name: cmms
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  agora_rtc_engine: ^5.3.0
  badges: ^2.0.3
  cached_network_image: ^3.2.1
  chewie: ^1.3.4
  country_picker: ^2.0.15
  cupertino_icons: ^1.0.2
  clipboard: ^0.1.3

  dio: ^4.0.4
  dismissible_page: ^0.7.3
  dots_indicator: ^2.1.0
  dotted_border: ^2.0.0+3
  dotted_line: ^3.1.0
  draggable_widget: ^2.0.0
  email_validator: ^2.0.1
  excel: ^2.1.0
  expandable_page_view: ^1.0.17
  file_picker: ^5.2.6
  # firebase_messaging: 12.0.3
  # firebase_analytics: ^10.0.3
  # firebase_core: ^2.1.0
  # firebase_crashlytics: ^3.0.2
  flowder: ^0.2.0
  
  flutter:
    sdk: flutter
  flutter_admin_scaffold: ^1.1.2
  flutter_branch_sdk: ^6.4.0
  flutter_facebook_auth: ^4.4.0+1
  flutter_html: ^3.0.0-alpha.5
  flutter_launcher_icons: ^0.10.0
  flutter_parsed_text: ^2.2.1
  flutter_rating_bar: ^4.0.1
  flutter_reorderable_grid_view: ^3.1.1
  flutter_scale_tap: ^1.0.5
  flutter_screenutil: ^5.5.3+2
  flutter_secure_storage: ^6.0.0
  flutter_share: ^2.0.0
  flutter_staggered_grid_view: ^0.6.0
  flutter_svg: ^1.0.3
  flutter_test:
    sdk: flutter
  geocoding: ^2.0.2
  geolocator: ^9.0.1
  get: ^4.6.5
  google_sign_in: ^5.4.2
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  http: ^0.13.4
  image_cropper: ^3.0.1
  # image_editor_plus:
  #   path: image_editor_plus
  image_gallery_saver: ^1.7.1
  image_picker: ^0.8.4+4
  image_viewer: ^1.5.0
  internet_connection_checker: ^0.0.1+1
  intl: ^0.17.0
  intl_phone_number_input: ^0.7.0+2
  loading_animation_widget: ^1.1.0+1
  loading_overlay_pro: ^2.1.1
  location: ^4.4.0
  logger: ^1.0.0
  mime: ^1.0.3
  # mixpanel_flutter: ^2.0.0
  mqtt_client: 9.6.1
  # onesignal_flutter: ^3.4.1
  open_mail_app: ^0.4.5
  open_store: ^0.5.0
  otp_autofill: ^2.1.0
  package_info_plus: ^1.4.3+1
  path_provider: ^2.0.9
  percent_indicator: ^4.0.0
  permission_handler: ^10.0.0
  photo_manager: ^2.0.8
  pin_code_fields: ^7.3.0
  pinch_zoom_image_last: ^0.4.1
  pip_view: ^0.9.7
  pull_to_refresh: ^2.0.0
  razorpay_flutter: ^1.3.2
  readmore: ^2.1.0
  scrollable_positioned_list: ^0.3.2
  scrollable_table_view: ^1.0.1
  share: ^2.0.4
  shimmer: ^2.0.0
  sign_in_with_apple: ^4.1.0
  smooth_page_indicator: ^1.0.0+2
  story_view: ^0.14.0
  super_banners: ^0.0.1
  timeago: ^3.3.0
  url_launcher: ^6.1.6
  video_player: ^2.4.4
  video_thumbnail: ^0.5.3
  visibility_detector: ^0.3.3
  wakelock: ^0.6.2
  # webview_flutter: ^3.0.4
  json_annotation: ^4.8.0
  device_info_plus_web: ^5.0.0
  multi_select_flutter: ^4.1.3
  dropdown_search: ^5.0.6
  flutter_form_builder: ^7.7.0
  # date_range_picker: ^1.0.7
  easy_sidemenu: ^0.4.1+1
  flutter_dropzone: ^3.0.5
  http_parser: ^4.0.2
  data_table_2: ^2.4.1
  rxdart: ^0.27.7
  filesize: ^2.0.1
  synchronized: ^3.0.1
  printing: ^5.6.0
  syncfusion_flutter_datepicker: ^19.1.55-beta
  html_unescape: ^2.0.0
  pdf: ^3.8.4


dev_dependencies:
  hive_generator: 
  build_runner: ^2.3.3
  json_serializable: ^6.6.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/cmms_logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/files/
    - assets/

    


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 600
